// Gallery Detail Icons
// Re-exported from centralized icon library for backward compatibility
// New code should import directly from @/components/ui/icons

export {
  EditIcon,
  PlusIcon,
  GridIcon,
  UploadIcon,
  ZoomIcon,
  PhotoIcon,
  ChevronRightIcon,
  LinkIcon,
  CopyIcon,
  ExternalLinkIcon,
  DownloadIcon,
  EmailIcon,
  DuplicateIcon,
  ProjectIcon,
  TrashIcon,
  PhoneIcon,
  QRIcon,
  CreateIcon,
  SendIcon,
  EyeIcon,
  CreditCardIcon,
  NoteIcon,
  ClockIcon,
  InvoiceIcon,
  AlertIcon,
  CheckboxIcon,
  StarIcon,
  CheckIcon,
  ExportIcon,
  ChartIcon,
  DesktopIcon,
  MobileIcon,
  TabletIcon,
  HeartIcon,
  ArchiveIcon,
  FilterIcon,
  CommentIcon,
  CommentBubbleIcon,
  XIcon as CloseIcon,
  ExpiredIcon,
  CalendarIcon,
  PreviewIcon,
  WarningIcon,
  GripIcon,
  FolderPlusIcon,
  SettingsIcon,
  LayersIcon,
  ListIcon,
} from "@/components/ui/icons";
