import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  Image,
  StyleSheet,
} from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    padding: 40,
    backgroundColor: "#ffffff",
    fontFamily: "Helvetica",
  },
  header: {
    marginBottom: 30,
    borderBottomWidth: 2,
    borderBottomColor: "#e5e5e5",
    paddingBottom: 20,
  },
  headerTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  logo: {
    width: 80,
    height: 40,
    objectFit: "contain",
  },
  headerInfo: {
    textAlign: "right",
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#1a1a1a",
    marginBottom: 5,
  },
  subtitle: {
    fontSize: 12,
    color: "#666666",
    marginBottom: 3,
  },
  description: {
    fontSize: 10,
    color: "#888888",
    marginTop: 10,
    maxWidth: "100%",
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-start",
    gap: 15,
  },
  photoContainer: {
    width: "30%",
    marginBottom: 20,
  },
  photoWrapper: {
    backgroundColor: "#f5f5f5",
    borderRadius: 4,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#e5e5e5",
  },
  photo: {
    width: "100%",
    height: 120,
    objectFit: "cover",
  },
  photoInfo: {
    padding: 8,
    backgroundColor: "#ffffff",
    borderTopWidth: 1,
    borderTopColor: "#e5e5e5",
  },
  photoNumber: {
    fontSize: 10,
    fontWeight: "bold",
    color: "#1a1a1a",
  },
  photoFilename: {
    fontSize: 8,
    color: "#888888",
    marginTop: 2,
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: "#e5e5e5",
  },
  footerText: {
    fontSize: 8,
    color: "#888888",
  },
  pageNumber: {
    fontSize: 8,
    color: "#888888",
  },
});

interface Photo {
  id: string;
  url: string;
  filename: string;
  number: number;
}

interface ProofSheetDocumentProps {
  galleryName: string;
  galleryDescription?: string;
  clientName?: string;
  photographerName: string;
  logoUrl?: string;
  createdAt: string;
  photos: Photo[];
}

const PHOTOS_PER_PAGE = 9;

export function ProofSheetDocument({
  galleryName,
  galleryDescription,
  clientName,
  photographerName,
  logoUrl,
  createdAt,
  photos,
}: ProofSheetDocumentProps) {
  // Split photos into pages
  const pages: Photo[][] = [];
  for (let i = 0; i < photos.length; i += PHOTOS_PER_PAGE) {
    pages.push(photos.slice(i, i + PHOTOS_PER_PAGE));
  }

  const formattedDate = new Date(createdAt).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <Document>
      {pages.map((pagePhotos, pageIndex) => (
        <Page key={pageIndex} size="A4" style={styles.page}>
          {/* Header - only on first page */}
          {pageIndex === 0 && (
            <View style={styles.header}>
              <View style={styles.headerTop}>
                <View>
                  <Text style={styles.title}>{galleryName}</Text>
                  <Text style={styles.subtitle}>Proof Sheet</Text>
                </View>
                <View style={styles.headerInfo}>
                  {logoUrl && <Image style={styles.logo} src={logoUrl} />}
                  <Text style={styles.subtitle}>{photographerName}</Text>
                  {clientName && <Text style={styles.subtitle}>For: {clientName}</Text>}
                  <Text style={styles.subtitle}>{formattedDate}</Text>
                </View>
              </View>
              {galleryDescription && (
                <Text style={styles.description}>{galleryDescription}</Text>
              )}
            </View>
          )}

          {/* Photo Grid */}
          <View style={styles.grid}>
            {pagePhotos.map((photo) => (
              <View key={photo.id} style={styles.photoContainer}>
                <View style={styles.photoWrapper}>
                  <Image style={styles.photo} src={photo.url} />
                  <View style={styles.photoInfo}>
                    <Text style={styles.photoNumber}>#{photo.number}</Text>
                    <Text style={styles.photoFilename}>
                      {photo.filename.length > 25
                        ? photo.filename.substring(0, 22) + "..."
                        : photo.filename}
                    </Text>
                  </View>
                </View>
              </View>
            ))}
          </View>

          {/* Footer */}
          <View style={styles.footer} fixed>
            <Text style={styles.footerText}>
              {galleryName} • {photos.length} photos • Generated by PhotoProOS
            </Text>
            <Text
              style={styles.pageNumber}
              render={({ pageNumber, totalPages }) =>
                `Page ${pageNumber} of ${totalPages}`
              }
            />
          </View>
        </Page>
      ))}
    </Document>
  );
}
