import type { DesignTemplate, DesignElement } from "./design-editor";

// Helper to generate IDs
const generateId = () => `tpl_${Date.now()}_${Math.random().toString(36).slice(2, 9)}`;

// Instagram Post - Just Listed
const instagramJustListed: DesignTemplate = {
  id: "instagram-just-listed",
  name: "Just Listed - Instagram",
  width: 1080,
  height: 1080,
  backgroundColor: "#1a1a2e",
  category: "social",
  elements: [
    {
      id: generateId(),
      type: "shape",
      x: 0,
      y: 0,
      width: 1080,
      height: 1080,
      rotation: 0,
      content: "rectangle",
      styles: {
        backgroundColor: "#0f0f23",
        opacity: 1,
      },
      layerOrder: 0,
      visible: true,
    },
    {
      id: generateId(),
      type: "image",
      x: 40,
      y: 40,
      width: 1000,
      height: 600,
      rotation: 0,
      content: "",
      styles: {
        borderRadius: 16,
      },
      layerOrder: 1,
      visible: true,
    },
    {
      id: generateId(),
      type: "shape",
      x: 40,
      y: 650,
      width: 200,
      height: 40,
      rotation: 0,
      content: "rectangle",
      styles: {
        backgroundColor: "#3b82f6",
        borderRadius: 20,
      },
      layerOrder: 2,
      visible: true,
    },
    {
      id: generateId(),
      type: "text",
      x: 60,
      y: 654,
      width: 160,
      height: 32,
      rotation: 0,
      content: "JUST LISTED",
      styles: {
        fontFamily: "Inter",
        fontSize: 14,
        fontWeight: "bold",
        color: "#ffffff",
        textAlign: "center",
      },
      layerOrder: 3,
      visible: true,
    },
    {
      id: generateId(),
      type: "placeholder",
      x: 40,
      y: 710,
      width: 1000,
      height: 60,
      rotation: 0,
      content: "{{address}}",
      styles: {
        fontFamily: "Playfair Display",
        fontSize: 36,
        fontWeight: "bold",
        color: "#ffffff",
        textAlign: "left",
      },
      layerOrder: 4,
      visible: true,
    },
    {
      id: generateId(),
      type: "placeholder",
      x: 40,
      y: 780,
      width: 400,
      height: 50,
      rotation: 0,
      content: "{{price}}",
      styles: {
        fontFamily: "Inter",
        fontSize: 32,
        fontWeight: "600",
        color: "#3b82f6",
        textAlign: "left",
      },
      layerOrder: 5,
      visible: true,
    },
    {
      id: generateId(),
      type: "text",
      x: 40,
      y: 850,
      width: 700,
      height: 40,
      rotation: 0,
      content: "{{bedrooms}} Beds • {{bathrooms}} Baths • {{sqft}} Sq Ft",
      styles: {
        fontFamily: "Inter",
        fontSize: 20,
        fontWeight: "normal",
        color: "#a0a0a0",
        textAlign: "left",
      },
      layerOrder: 6,
      visible: true,
    },
    {
      id: generateId(),
      type: "shape",
      x: 0,
      y: 920,
      width: 1080,
      height: 160,
      rotation: 0,
      content: "rectangle",
      styles: {
        backgroundColor: "#141428",
        opacity: 1,
      },
      layerOrder: 7,
      visible: true,
    },
    {
      id: generateId(),
      type: "logo",
      x: 40,
      y: 950,
      width: 80,
      height: 80,
      rotation: 0,
      content: "{{logoUrl}}",
      styles: {},
      layerOrder: 8,
      visible: true,
    },
    {
      id: generateId(),
      type: "placeholder",
      x: 140,
      y: 965,
      width: 400,
      height: 30,
      rotation: 0,
      content: "{{agentName}}",
      styles: {
        fontFamily: "Inter",
        fontSize: 20,
        fontWeight: "600",
        color: "#ffffff",
        textAlign: "left",
      },
      layerOrder: 9,
      visible: true,
    },
    {
      id: generateId(),
      type: "placeholder",
      x: 140,
      y: 1000,
      width: 400,
      height: 24,
      rotation: 0,
      content: "{{agentPhone}}",
      styles: {
        fontFamily: "Inter",
        fontSize: 16,
        fontWeight: "normal",
        color: "#a0a0a0",
        textAlign: "left",
      },
      layerOrder: 10,
      visible: true,
    },
  ],
};

// Instagram Story - Property Showcase
const instagramStory: DesignTemplate = {
  id: "instagram-story-showcase",
  name: "Property Showcase - Story",
  width: 1080,
  height: 1920,
  backgroundColor: "#0f0f23",
  category: "social",
  elements: [
    {
      id: generateId(),
      type: "image",
      x: 0,
      y: 0,
      width: 1080,
      height: 1920,
      rotation: 0,
      content: "",
      styles: {
        opacity: 0.6,
      },
      layerOrder: 0,
      visible: true,
    },
    {
      id: generateId(),
      type: "shape",
      x: 0,
      y: 1200,
      width: 1080,
      height: 720,
      rotation: 0,
      content: "rectangle",
      styles: {
        backgroundColor: "linear-gradient(transparent, #000000)",
        opacity: 0.9,
      },
      layerOrder: 1,
      visible: true,
    },
    {
      id: generateId(),
      type: "shape",
      x: 60,
      y: 80,
      width: 180,
      height: 50,
      rotation: 0,
      content: "rectangle",
      styles: {
        backgroundColor: "#3b82f6",
        borderRadius: 25,
      },
      layerOrder: 2,
      visible: true,
    },
    {
      id: generateId(),
      type: "text",
      x: 60,
      y: 88,
      width: 180,
      height: 34,
      rotation: 0,
      content: "FOR SALE",
      styles: {
        fontFamily: "Inter",
        fontSize: 18,
        fontWeight: "bold",
        color: "#ffffff",
        textAlign: "center",
      },
      layerOrder: 3,
      visible: true,
    },
    {
      id: generateId(),
      type: "placeholder",
      x: 60,
      y: 1400,
      width: 960,
      height: 80,
      rotation: 0,
      content: "{{address}}",
      styles: {
        fontFamily: "Playfair Display",
        fontSize: 48,
        fontWeight: "bold",
        color: "#ffffff",
        textAlign: "left",
      },
      layerOrder: 4,
      visible: true,
    },
    {
      id: generateId(),
      type: "placeholder",
      x: 60,
      y: 1500,
      width: 400,
      height: 60,
      rotation: 0,
      content: "{{price}}",
      styles: {
        fontFamily: "Inter",
        fontSize: 42,
        fontWeight: "bold",
        color: "#3b82f6",
        textAlign: "left",
      },
      layerOrder: 5,
      visible: true,
    },
    {
      id: generateId(),
      type: "shape",
      x: 60,
      y: 1600,
      width: 960,
      height: 2,
      rotation: 0,
      content: "rectangle",
      styles: {
        backgroundColor: "#ffffff",
        opacity: 0.3,
      },
      layerOrder: 6,
      visible: true,
    },
    {
      id: generateId(),
      type: "text",
      x: 60,
      y: 1640,
      width: 300,
      height: 80,
      rotation: 0,
      content: "{{bedrooms}}\nBedrooms",
      styles: {
        fontFamily: "Inter",
        fontSize: 24,
        fontWeight: "600",
        color: "#ffffff",
        textAlign: "center",
      },
      layerOrder: 7,
      visible: true,
    },
    {
      id: generateId(),
      type: "text",
      x: 390,
      y: 1640,
      width: 300,
      height: 80,
      rotation: 0,
      content: "{{bathrooms}}\nBathrooms",
      styles: {
        fontFamily: "Inter",
        fontSize: 24,
        fontWeight: "600",
        color: "#ffffff",
        textAlign: "center",
      },
      layerOrder: 8,
      visible: true,
    },
    {
      id: generateId(),
      type: "text",
      x: 720,
      y: 1640,
      width: 300,
      height: 80,
      rotation: 0,
      content: "{{sqft}}\nSq Ft",
      styles: {
        fontFamily: "Inter",
        fontSize: 24,
        fontWeight: "600",
        color: "#ffffff",
        textAlign: "center",
      },
      layerOrder: 9,
      visible: true,
    },
    {
      id: generateId(),
      type: "logo",
      x: 60,
      y: 1780,
      width: 120,
      height: 60,
      rotation: 0,
      content: "{{logoUrl}}",
      styles: {},
      layerOrder: 10,
      visible: true,
    },
    {
      id: generateId(),
      type: "text",
      x: 200,
      y: 1790,
      width: 300,
      height: 40,
      rotation: 0,
      content: "Swipe Up for Details",
      styles: {
        fontFamily: "Inter",
        fontSize: 18,
        fontWeight: "500",
        color: "#a0a0a0",
        textAlign: "left",
      },
      layerOrder: 11,
      visible: true,
    },
  ],
};

// Facebook Post
const facebookPost: DesignTemplate = {
  id: "facebook-post",
  name: "Property Post - Facebook",
  width: 1200,
  height: 628,
  backgroundColor: "#ffffff",
  category: "social",
  elements: [
    {
      id: generateId(),
      type: "image",
      x: 0,
      y: 0,
      width: 628,
      height: 628,
      rotation: 0,
      content: "",
      styles: {},
      layerOrder: 0,
      visible: true,
    },
    {
      id: generateId(),
      type: "shape",
      x: 628,
      y: 0,
      width: 572,
      height: 628,
      rotation: 0,
      content: "rectangle",
      styles: {
        backgroundColor: "#1a1a2e",
      },
      layerOrder: 1,
      visible: true,
    },
    {
      id: generateId(),
      type: "placeholder",
      x: 668,
      y: 60,
      width: 492,
      height: 100,
      rotation: 0,
      content: "{{address}}",
      styles: {
        fontFamily: "Playfair Display",
        fontSize: 32,
        fontWeight: "bold",
        color: "#ffffff",
        textAlign: "left",
      },
      layerOrder: 2,
      visible: true,
    },
    {
      id: generateId(),
      type: "placeholder",
      x: 668,
      y: 170,
      width: 300,
      height: 50,
      rotation: 0,
      content: "{{price}}",
      styles: {
        fontFamily: "Inter",
        fontSize: 36,
        fontWeight: "bold",
        color: "#3b82f6",
        textAlign: "left",
      },
      layerOrder: 3,
      visible: true,
    },
    {
      id: generateId(),
      type: "shape",
      x: 668,
      y: 240,
      width: 492,
      height: 1,
      rotation: 0,
      content: "rectangle",
      styles: {
        backgroundColor: "#ffffff",
        opacity: 0.2,
      },
      layerOrder: 4,
      visible: true,
    },
    {
      id: generateId(),
      type: "text",
      x: 668,
      y: 270,
      width: 150,
      height: 80,
      rotation: 0,
      content: "{{bedrooms}}\nBedrooms",
      styles: {
        fontFamily: "Inter",
        fontSize: 18,
        fontWeight: "600",
        color: "#ffffff",
        textAlign: "center",
      },
      layerOrder: 5,
      visible: true,
    },
    {
      id: generateId(),
      type: "text",
      x: 838,
      y: 270,
      width: 150,
      height: 80,
      rotation: 0,
      content: "{{bathrooms}}\nBathrooms",
      styles: {
        fontFamily: "Inter",
        fontSize: 18,
        fontWeight: "600",
        color: "#ffffff",
        textAlign: "center",
      },
      layerOrder: 6,
      visible: true,
    },
    {
      id: generateId(),
      type: "text",
      x: 1008,
      y: 270,
      width: 150,
      height: 80,
      rotation: 0,
      content: "{{sqft}}\nSq Ft",
      styles: {
        fontFamily: "Inter",
        fontSize: 18,
        fontWeight: "600",
        color: "#ffffff",
        textAlign: "center",
      },
      layerOrder: 7,
      visible: true,
    },
    {
      id: generateId(),
      type: "placeholder",
      x: 668,
      y: 380,
      width: 492,
      height: 100,
      rotation: 0,
      content: "{{description}}",
      styles: {
        fontFamily: "Inter",
        fontSize: 14,
        fontWeight: "normal",
        color: "#a0a0a0",
        textAlign: "left",
      },
      layerOrder: 8,
      visible: true,
    },
    {
      id: generateId(),
      type: "shape",
      x: 668,
      y: 500,
      width: 492,
      height: 1,
      rotation: 0,
      content: "rectangle",
      styles: {
        backgroundColor: "#ffffff",
        opacity: 0.2,
      },
      layerOrder: 9,
      visible: true,
    },
    {
      id: generateId(),
      type: "logo",
      x: 668,
      y: 530,
      width: 60,
      height: 60,
      rotation: 0,
      content: "{{logoUrl}}",
      styles: {},
      layerOrder: 10,
      visible: true,
    },
    {
      id: generateId(),
      type: "placeholder",
      x: 748,
      y: 540,
      width: 300,
      height: 24,
      rotation: 0,
      content: "{{agentName}}",
      styles: {
        fontFamily: "Inter",
        fontSize: 16,
        fontWeight: "600",
        color: "#ffffff",
        textAlign: "left",
      },
      layerOrder: 11,
      visible: true,
    },
    {
      id: generateId(),
      type: "placeholder",
      x: 748,
      y: 568,
      width: 300,
      height: 20,
      rotation: 0,
      content: "{{agentPhone}}",
      styles: {
        fontFamily: "Inter",
        fontSize: 14,
        fontWeight: "normal",
        color: "#a0a0a0",
        textAlign: "left",
      },
      layerOrder: 12,
      visible: true,
    },
  ],
};

// Print Flyer - 8.5x11
const printFlyer: DesignTemplate = {
  id: "print-flyer-8x11",
  name: "Property Flyer - 8.5x11",
  width: 2550,
  height: 3300,
  backgroundColor: "#ffffff",
  category: "print",
  elements: [
    {
      id: generateId(),
      type: "image",
      x: 0,
      y: 0,
      width: 2550,
      height: 1700,
      rotation: 0,
      content: "",
      styles: {},
      layerOrder: 0,
      visible: true,
    },
    {
      id: generateId(),
      type: "shape",
      x: 100,
      y: 100,
      width: 400,
      height: 80,
      rotation: 0,
      content: "rectangle",
      styles: {
        backgroundColor: "#3b82f6",
        borderRadius: 8,
      },
      layerOrder: 1,
      visible: true,
    },
    {
      id: generateId(),
      type: "text",
      x: 100,
      y: 115,
      width: 400,
      height: 50,
      rotation: 0,
      content: "FOR SALE",
      styles: {
        fontFamily: "Inter",
        fontSize: 32,
        fontWeight: "bold",
        color: "#ffffff",
        textAlign: "center",
      },
      layerOrder: 2,
      visible: true,
    },
    {
      id: generateId(),
      type: "placeholder",
      x: 100,
      y: 1800,
      width: 2350,
      height: 120,
      rotation: 0,
      content: "{{address}}",
      styles: {
        fontFamily: "Playfair Display",
        fontSize: 72,
        fontWeight: "bold",
        color: "#1a1a2e",
        textAlign: "center",
      },
      layerOrder: 3,
      visible: true,
    },
    {
      id: generateId(),
      type: "placeholder",
      x: 100,
      y: 1940,
      width: 2350,
      height: 80,
      rotation: 0,
      content: "{{price}}",
      styles: {
        fontFamily: "Inter",
        fontSize: 56,
        fontWeight: "bold",
        color: "#3b82f6",
        textAlign: "center",
      },
      layerOrder: 4,
      visible: true,
    },
    {
      id: generateId(),
      type: "shape",
      x: 100,
      y: 2060,
      width: 2350,
      height: 2,
      rotation: 0,
      content: "rectangle",
      styles: {
        backgroundColor: "#e0e0e0",
      },
      layerOrder: 5,
      visible: true,
    },
    {
      id: generateId(),
      type: "text",
      x: 100,
      y: 2100,
      width: 780,
      height: 150,
      rotation: 0,
      content: "{{bedrooms}}\nBedrooms",
      styles: {
        fontFamily: "Inter",
        fontSize: 36,
        fontWeight: "600",
        color: "#1a1a2e",
        textAlign: "center",
      },
      layerOrder: 6,
      visible: true,
    },
    {
      id: generateId(),
      type: "text",
      x: 885,
      y: 2100,
      width: 780,
      height: 150,
      rotation: 0,
      content: "{{bathrooms}}\nBathrooms",
      styles: {
        fontFamily: "Inter",
        fontSize: 36,
        fontWeight: "600",
        color: "#1a1a2e",
        textAlign: "center",
      },
      layerOrder: 7,
      visible: true,
    },
    {
      id: generateId(),
      type: "text",
      x: 1670,
      y: 2100,
      width: 780,
      height: 150,
      rotation: 0,
      content: "{{sqft}}\nSq Ft",
      styles: {
        fontFamily: "Inter",
        fontSize: 36,
        fontWeight: "600",
        color: "#1a1a2e",
        textAlign: "center",
      },
      layerOrder: 8,
      visible: true,
    },
    {
      id: generateId(),
      type: "placeholder",
      x: 100,
      y: 2300,
      width: 2350,
      height: 300,
      rotation: 0,
      content: "{{description}}",
      styles: {
        fontFamily: "Inter",
        fontSize: 28,
        fontWeight: "normal",
        color: "#666666",
        textAlign: "center",
        padding: 20,
      },
      layerOrder: 9,
      visible: true,
    },
    {
      id: generateId(),
      type: "shape",
      x: 0,
      y: 2700,
      width: 2550,
      height: 600,
      rotation: 0,
      content: "rectangle",
      styles: {
        backgroundColor: "#1a1a2e",
      },
      layerOrder: 10,
      visible: true,
    },
    {
      id: generateId(),
      type: "logo",
      x: 100,
      y: 2800,
      width: 200,
      height: 200,
      rotation: 0,
      content: "{{logoUrl}}",
      styles: {},
      layerOrder: 11,
      visible: true,
    },
    {
      id: generateId(),
      type: "placeholder",
      x: 350,
      y: 2850,
      width: 600,
      height: 50,
      rotation: 0,
      content: "{{agentName}}",
      styles: {
        fontFamily: "Inter",
        fontSize: 36,
        fontWeight: "bold",
        color: "#ffffff",
        textAlign: "left",
      },
      layerOrder: 12,
      visible: true,
    },
    {
      id: generateId(),
      type: "placeholder",
      x: 350,
      y: 2910,
      width: 600,
      height: 40,
      rotation: 0,
      content: "{{agentPhone}} | {{agentEmail}}",
      styles: {
        fontFamily: "Inter",
        fontSize: 24,
        fontWeight: "normal",
        color: "#a0a0a0",
        textAlign: "left",
      },
      layerOrder: 13,
      visible: true,
    },
    {
      id: generateId(),
      type: "placeholder",
      x: 350,
      y: 2960,
      width: 600,
      height: 40,
      rotation: 0,
      content: "{{companyName}}",
      styles: {
        fontFamily: "Inter",
        fontSize: 24,
        fontWeight: "normal",
        color: "#a0a0a0",
        textAlign: "left",
      },
      layerOrder: 14,
      visible: true,
    },
  ],
};

// Postcard
const postcard: DesignTemplate = {
  id: "postcard",
  name: "Postcard - 6x4",
  width: 1800,
  height: 1200,
  backgroundColor: "#ffffff",
  category: "print",
  elements: [
    {
      id: generateId(),
      type: "image",
      x: 0,
      y: 0,
      width: 1200,
      height: 1200,
      rotation: 0,
      content: "",
      styles: {},
      layerOrder: 0,
      visible: true,
    },
    {
      id: generateId(),
      type: "shape",
      x: 1200,
      y: 0,
      width: 600,
      height: 1200,
      rotation: 0,
      content: "rectangle",
      styles: {
        backgroundColor: "#1a1a2e",
      },
      layerOrder: 1,
      visible: true,
    },
    {
      id: generateId(),
      type: "text",
      x: 1240,
      y: 60,
      width: 520,
      height: 50,
      rotation: 0,
      content: "JUST LISTED",
      styles: {
        fontFamily: "Inter",
        fontSize: 24,
        fontWeight: "bold",
        color: "#3b82f6",
        textAlign: "center",
      },
      layerOrder: 2,
      visible: true,
    },
    {
      id: generateId(),
      type: "placeholder",
      x: 1240,
      y: 140,
      width: 520,
      height: 200,
      rotation: 0,
      content: "{{address}}",
      styles: {
        fontFamily: "Playfair Display",
        fontSize: 32,
        fontWeight: "bold",
        color: "#ffffff",
        textAlign: "center",
      },
      layerOrder: 3,
      visible: true,
    },
    {
      id: generateId(),
      type: "placeholder",
      x: 1240,
      y: 360,
      width: 520,
      height: 60,
      rotation: 0,
      content: "{{price}}",
      styles: {
        fontFamily: "Inter",
        fontSize: 40,
        fontWeight: "bold",
        color: "#3b82f6",
        textAlign: "center",
      },
      layerOrder: 4,
      visible: true,
    },
    {
      id: generateId(),
      type: "text",
      x: 1240,
      y: 450,
      width: 520,
      height: 40,
      rotation: 0,
      content: "{{bedrooms}} Beds | {{bathrooms}} Baths | {{sqft}} Sq Ft",
      styles: {
        fontFamily: "Inter",
        fontSize: 18,
        fontWeight: "normal",
        color: "#a0a0a0",
        textAlign: "center",
      },
      layerOrder: 5,
      visible: true,
    },
    {
      id: generateId(),
      type: "shape",
      x: 1280,
      y: 520,
      width: 440,
      height: 1,
      rotation: 0,
      content: "rectangle",
      styles: {
        backgroundColor: "#ffffff",
        opacity: 0.2,
      },
      layerOrder: 6,
      visible: true,
    },
    {
      id: generateId(),
      type: "placeholder",
      x: 1240,
      y: 560,
      width: 520,
      height: 300,
      rotation: 0,
      content: "{{description}}",
      styles: {
        fontFamily: "Inter",
        fontSize: 14,
        fontWeight: "normal",
        color: "#a0a0a0",
        textAlign: "center",
        padding: 10,
      },
      layerOrder: 7,
      visible: true,
    },
    {
      id: generateId(),
      type: "shape",
      x: 1200,
      y: 900,
      width: 600,
      height: 300,
      rotation: 0,
      content: "rectangle",
      styles: {
        backgroundColor: "#0f0f1e",
      },
      layerOrder: 8,
      visible: true,
    },
    {
      id: generateId(),
      type: "logo",
      x: 1240,
      y: 940,
      width: 100,
      height: 100,
      rotation: 0,
      content: "{{logoUrl}}",
      styles: {},
      layerOrder: 9,
      visible: true,
    },
    {
      id: generateId(),
      type: "placeholder",
      x: 1360,
      y: 960,
      width: 380,
      height: 30,
      rotation: 0,
      content: "{{agentName}}",
      styles: {
        fontFamily: "Inter",
        fontSize: 20,
        fontWeight: "bold",
        color: "#ffffff",
        textAlign: "left",
      },
      layerOrder: 10,
      visible: true,
    },
    {
      id: generateId(),
      type: "placeholder",
      x: 1360,
      y: 1000,
      width: 380,
      height: 24,
      rotation: 0,
      content: "{{agentPhone}}",
      styles: {
        fontFamily: "Inter",
        fontSize: 16,
        fontWeight: "normal",
        color: "#a0a0a0",
        textAlign: "left",
      },
      layerOrder: 11,
      visible: true,
    },
  ],
};

// Open House Template
const openHouse: DesignTemplate = {
  id: "open-house-sign",
  name: "Open House Sign",
  width: 1080,
  height: 1080,
  backgroundColor: "#1a1a2e",
  category: "event",
  elements: [
    {
      id: generateId(),
      type: "shape",
      x: 0,
      y: 0,
      width: 1080,
      height: 1080,
      rotation: 0,
      content: "rectangle",
      styles: {
        backgroundColor: "#3b82f6",
      },
      layerOrder: 0,
      visible: true,
    },
    {
      id: generateId(),
      type: "text",
      x: 0,
      y: 200,
      width: 1080,
      height: 120,
      rotation: 0,
      content: "OPEN HOUSE",
      styles: {
        fontFamily: "Inter",
        fontSize: 80,
        fontWeight: "bold",
        color: "#ffffff",
        textAlign: "center",
      },
      layerOrder: 1,
      visible: true,
    },
    {
      id: generateId(),
      type: "text",
      x: 0,
      y: 340,
      width: 1080,
      height: 80,
      rotation: 0,
      content: "Saturday & Sunday",
      styles: {
        fontFamily: "Inter",
        fontSize: 36,
        fontWeight: "600",
        color: "#ffffff",
        textAlign: "center",
        opacity: 0.9,
      },
      layerOrder: 2,
      visible: true,
    },
    {
      id: generateId(),
      type: "text",
      x: 0,
      y: 420,
      width: 1080,
      height: 80,
      rotation: 0,
      content: "1:00 PM - 4:00 PM",
      styles: {
        fontFamily: "Inter",
        fontSize: 48,
        fontWeight: "bold",
        color: "#ffffff",
        textAlign: "center",
      },
      layerOrder: 3,
      visible: true,
    },
    {
      id: generateId(),
      type: "shape",
      x: 100,
      y: 540,
      width: 880,
      height: 2,
      rotation: 0,
      content: "rectangle",
      styles: {
        backgroundColor: "#ffffff",
        opacity: 0.3,
      },
      layerOrder: 4,
      visible: true,
    },
    {
      id: generateId(),
      type: "placeholder",
      x: 40,
      y: 580,
      width: 1000,
      height: 120,
      rotation: 0,
      content: "{{address}}",
      styles: {
        fontFamily: "Playfair Display",
        fontSize: 40,
        fontWeight: "bold",
        color: "#ffffff",
        textAlign: "center",
      },
      layerOrder: 5,
      visible: true,
    },
    {
      id: generateId(),
      type: "placeholder",
      x: 40,
      y: 720,
      width: 1000,
      height: 60,
      rotation: 0,
      content: "{{price}}",
      styles: {
        fontFamily: "Inter",
        fontSize: 42,
        fontWeight: "bold",
        color: "#ffffff",
        textAlign: "center",
      },
      layerOrder: 6,
      visible: true,
    },
    {
      id: generateId(),
      type: "text",
      x: 40,
      y: 800,
      width: 1000,
      height: 40,
      rotation: 0,
      content: "{{bedrooms}} Beds • {{bathrooms}} Baths • {{sqft}} Sq Ft",
      styles: {
        fontFamily: "Inter",
        fontSize: 24,
        fontWeight: "normal",
        color: "#ffffff",
        textAlign: "center",
        opacity: 0.8,
      },
      layerOrder: 7,
      visible: true,
    },
    {
      id: generateId(),
      type: "shape",
      x: 0,
      y: 880,
      width: 1080,
      height: 200,
      rotation: 0,
      content: "rectangle",
      styles: {
        backgroundColor: "#1a1a2e",
      },
      layerOrder: 8,
      visible: true,
    },
    {
      id: generateId(),
      type: "logo",
      x: 100,
      y: 920,
      width: 120,
      height: 120,
      rotation: 0,
      content: "{{logoUrl}}",
      styles: {},
      layerOrder: 9,
      visible: true,
    },
    {
      id: generateId(),
      type: "placeholder",
      x: 260,
      y: 945,
      width: 600,
      height: 35,
      rotation: 0,
      content: "{{agentName}}",
      styles: {
        fontFamily: "Inter",
        fontSize: 26,
        fontWeight: "bold",
        color: "#ffffff",
        textAlign: "left",
      },
      layerOrder: 10,
      visible: true,
    },
    {
      id: generateId(),
      type: "placeholder",
      x: 260,
      y: 990,
      width: 600,
      height: 30,
      rotation: 0,
      content: "{{agentPhone}}",
      styles: {
        fontFamily: "Inter",
        fontSize: 20,
        fontWeight: "normal",
        color: "#a0a0a0",
        textAlign: "left",
      },
      layerOrder: 11,
      visible: true,
    },
  ],
};

// Export all templates
export const DESIGN_TEMPLATES: DesignTemplate[] = [
  instagramJustListed,
  instagramStory,
  facebookPost,
  printFlyer,
  postcard,
  openHouse,
];

// Template categories
export const TEMPLATE_CATEGORIES = [
  { id: "all", label: "All Templates" },
  { id: "social", label: "Social Media" },
  { id: "print", label: "Print" },
  { id: "event", label: "Events" },
];

// Get templates by category
export function getTemplatesByCategory(category: string): DesignTemplate[] {
  if (category === "all") return DESIGN_TEMPLATES;
  return DESIGN_TEMPLATES.filter((t) => t.category === category);
}

// Get template by ID
export function getTemplateById(id: string): DesignTemplate | undefined {
  return DESIGN_TEMPLATES.find((t) => t.id === id);
}
